services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
  backend:
    container_name: zamow-jedzenie-backend
    build: ./backend/zamow_jedzenie
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/zamow_jedzenie:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
        db:
          condition: service_healthy
  frontend:
    container_name: zamow-jedzenie-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BASE_URL=http://0.0.0.0:8000/
    depends_on:
      - backend
volumes:
  db:
    driver: local

# backend ip http://0.0.0.0:8000/
