# Generated by Django 4.0.5 on 2022-07-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Other', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('ratingCount', models.IntegerField()),
                ('ratingValue', models.DecimalField(decimal_places=2, max_digits=3)),
                ('minimalOrderCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliveryCost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.CharField(max_length=255)),
                ('categories', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurants.category')),
                ('restaurantId', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(to='restaurants.product')),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour_monday', models.TimeField()),
                ('to_hour_monday', models.TimeField()),
                ('from_hour_tuesday', models.TimeField()),
                ('to_hour_tuesday', models.TimeField()),
                ('from_hour_wednesday', models.TimeField()),
                ('to_hour_wednesday', models.TimeField()),
                ('from_hour_thursday', models.TimeField()),
                ('to_hour_thursday', models.TimeField()),
                ('from_hour_friday', models.TimeField()),
                ('to_hour_friday', models.TimeField()),
                ('from_hour_saturday', models.TimeField()),
                ('to_hour_saturday', models.TimeField()),
                ('from_hour_sunday', models.TimeField()),
                ('to_hour_sunday', models.TimeField()),
                ('restaurant', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
