# Generated by Django 4.0.5 on 2022-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_product_restaurantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='restaurantId',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='products',
            field=models.ManyToManyField(to='restaurants.product'),
        ),
    ]
