# Generated by Django 4.0.5 on 2022-06-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_product_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='items',
        ),
        migrations.AddField(
            model_name='product',
            name='restaurantId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
